#date > ~/vagrant_provisioned_at
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_download_insecure=true
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

  config.vm.define "ci-server" do |ciserver|
    ciserver.vm.network "private_network", ip: '192.168.56.70'
    ciserver.vm.hostname = "ci-server"
    config.vm.provision :docker
    config.vm.provision :docker_compose, compose_version: "1.29.2"
    ciserver.vm.provision :file, source:"../docker/docker-compose.ci.yml", destination:"docker-compose.yml"
    ciserver.vm.provision :shell , inline:"sudo chmod 777 /var/run/docker.sock"
    ciserver.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", compose_version: "1.29.2", run: "always"
  end

  config.vm.define "server-2" do |server2|
    server2.vm.network "private_network", ip: '192.168.56.71'
    server2.vm.hostname = "server-2"
    config.vm.provision :docker
  #  server2.vm.provision :file, source: "Converter", destination: "Converter"
  #  server2.vm.provision "shell", inline: "docker compose -f /home/vagrant/Converter/Docker-compose.yaml up -d"
  end
end