# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_download_insecure=true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision :docker

  config.vm.define "ci-server" do |ciserver|
    ciserver.vm.network "private_network", ip: '192.168.56.70'
    ciserver.vm.hostname = "ci-server"
    ciserver.vm.provision :file, source:"../docker/docker-compose.ci.yml", destination:"docker-compose.yml"
    ciserver.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
    ciserver.vm.provision :shell , inline:"sudo chmod 777 /var/run/docker.sock"
  end

  config.vm.define "server-3" do |cd|
    cd.vm.network "private_network", ip: '192.168.56.72'
    cd.vm.hostname = "cd-server"
    cd.vm.provision :file, source:"../docker/docker-compose.cd.yml", destination:"docker-compose.yml"
    cd.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
    cd.vm.provision :shell , inline:"sudo chmod 777 /var/run/docker.sock"
  end

  config.vm.define "server-2" do |server2|
    server2.vm.network "private_network", ip: '192.168.56.71'
    server2.vm.hostname = "server-2"
  end
end